// Mocks generated by Mockito 5.4.6 from annotations
// in time_tracking_kanaban/test/features/timer/presentation/cubit/task_history_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;
import 'package:time_tracking_kanaban/core/usecases/usecase.dart' as _i6;
import 'package:time_tracking_kanaban/core/utils/result.dart' as _i4;
import 'package:time_tracking_kanaban/features/timer/domain/entities/task_timer_summary.dart'
    as _i5;
import 'package:time_tracking_kanaban/features/timer/domain/usecases/get_completed_tasks_history_usecase.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [GetCompletedTasksHistoryUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetCompletedTasksHistoryUseCase extends _i1.Mock
    implements _i2.GetCompletedTasksHistoryUseCase {
  MockGetCompletedTasksHistoryUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Result<List<_i5.TaskTimerSummary>>> call(
    _i6.NoParams? params,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue:
                _i3.Future<_i4.Result<List<_i5.TaskTimerSummary>>>.value(
                  _i7.dummyValue<_i4.Result<List<_i5.TaskTimerSummary>>>(
                    this,
                    Invocation.method(#call, [params]),
                  ),
                ),
          )
          as _i3.Future<_i4.Result<List<_i5.TaskTimerSummary>>>);
}
