// Mocks generated by Mockito 5.4.6 from annotations
// in time_tracking_kanaban/test/features/timer/presentation/bloc/timer_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;
import 'package:time_tracking_kanaban/core/usecases/usecase.dart' as _i8;
import 'package:time_tracking_kanaban/core/utils/result.dart' as _i4;
import 'package:time_tracking_kanaban/features/timer/domain/entities/time_log.dart'
    as _i5;
import 'package:time_tracking_kanaban/features/timer/domain/usecases/get_active_timer_usecase.dart'
    as _i11;
import 'package:time_tracking_kanaban/features/timer/domain/usecases/pause_timer_usecase.dart'
    as _i7;
import 'package:time_tracking_kanaban/features/timer/domain/usecases/resume_timer_usecase.dart'
    as _i9;
import 'package:time_tracking_kanaban/features/timer/domain/usecases/start_timer_usecase.dart'
    as _i2;
import 'package:time_tracking_kanaban/features/timer/domain/usecases/stop_timer_usecase.dart'
    as _i10;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [StartTimerUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockStartTimerUseCase extends _i1.Mock implements _i2.StartTimerUseCase {
  MockStartTimerUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Result<_i5.TimeLog>> call(_i2.StartTimerParams? params) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue: _i3.Future<_i4.Result<_i5.TimeLog>>.value(
              _i6.dummyValue<_i4.Result<_i5.TimeLog>>(
                this,
                Invocation.method(#call, [params]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<_i5.TimeLog>>);
}

/// A class which mocks [PauseTimerUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockPauseTimerUseCase extends _i1.Mock implements _i7.PauseTimerUseCase {
  MockPauseTimerUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Result<_i5.TimeLog>> call(_i8.NoParams? params) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue: _i3.Future<_i4.Result<_i5.TimeLog>>.value(
              _i6.dummyValue<_i4.Result<_i5.TimeLog>>(
                this,
                Invocation.method(#call, [params]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<_i5.TimeLog>>);
}

/// A class which mocks [ResumeTimerUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockResumeTimerUseCase extends _i1.Mock
    implements _i9.ResumeTimerUseCase {
  MockResumeTimerUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Result<_i5.TimeLog>> call(_i9.ResumeTimerParams? params) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue: _i3.Future<_i4.Result<_i5.TimeLog>>.value(
              _i6.dummyValue<_i4.Result<_i5.TimeLog>>(
                this,
                Invocation.method(#call, [params]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<_i5.TimeLog>>);
}

/// A class which mocks [StopTimerUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockStopTimerUseCase extends _i1.Mock implements _i10.StopTimerUseCase {
  MockStopTimerUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Result<_i5.TimeLog>> call(_i8.NoParams? params) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue: _i3.Future<_i4.Result<_i5.TimeLog>>.value(
              _i6.dummyValue<_i4.Result<_i5.TimeLog>>(
                this,
                Invocation.method(#call, [params]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<_i5.TimeLog>>);
}

/// A class which mocks [GetActiveTimerUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetActiveTimerUseCase extends _i1.Mock
    implements _i11.GetActiveTimerUseCase {
  MockGetActiveTimerUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Result<_i5.TimeLog?>> call(_i8.NoParams? params) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue: _i3.Future<_i4.Result<_i5.TimeLog?>>.value(
              _i6.dummyValue<_i4.Result<_i5.TimeLog?>>(
                this,
                Invocation.method(#call, [params]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<_i5.TimeLog?>>);
}
