// Mocks generated by Mockito 5.4.6 from annotations
// in time_tracking_kanaban/test/features/tasks/presentation/bloc/kanban_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;
import 'package:time_tracking_kanaban/core/usecases/usecase.dart' as _i7;
import 'package:time_tracking_kanaban/core/utils/result.dart' as _i5;
import 'package:time_tracking_kanaban/features/tasks/domain/entities/section.dart'
    as _i15;
import 'package:time_tracking_kanaban/features/tasks/domain/entities/task.dart'
    as _i6;
import 'package:time_tracking_kanaban/features/tasks/domain/repository/tasks_repository.dart'
    as _i2;
import 'package:time_tracking_kanaban/features/tasks/domain/usecases/add_task_usecase.dart'
    as _i10;
import 'package:time_tracking_kanaban/features/tasks/domain/usecases/close_task_usecase.dart'
    as _i12;
import 'package:time_tracking_kanaban/features/tasks/domain/usecases/delete_task_usecase.dart'
    as _i13;
import 'package:time_tracking_kanaban/features/tasks/domain/usecases/get_sections_usecase.dart'
    as _i14;
import 'package:time_tracking_kanaban/features/tasks/domain/usecases/get_tasks_usecase.dart'
    as _i3;
import 'package:time_tracking_kanaban/features/tasks/domain/usecases/move_task_usecase.dart'
    as _i9;
import 'package:time_tracking_kanaban/features/tasks/domain/usecases/update_task_usecase.dart'
    as _i11;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeTasksRepository_0 extends _i1.SmartFake
    implements _i2.TasksRepository {
  _FakeTasksRepository_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [GetTasksUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetTasksUseCase extends _i1.Mock implements _i3.GetTasksUseCase {
  MockGetTasksUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.TasksRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeTasksRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.TasksRepository);

  @override
  _i4.Future<_i5.Result<List<_i6.Task>>> call(_i7.NoParams? params) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue: _i4.Future<_i5.Result<List<_i6.Task>>>.value(
              _i8.dummyValue<_i5.Result<List<_i6.Task>>>(
                this,
                Invocation.method(#call, [params]),
              ),
            ),
          )
          as _i4.Future<_i5.Result<List<_i6.Task>>>);
}

/// A class which mocks [MoveTaskUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockMoveTaskUseCase extends _i1.Mock implements _i9.MoveTaskUseCase {
  MockMoveTaskUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.TasksRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeTasksRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.TasksRepository);

  @override
  _i4.Future<_i5.Result<_i6.Task>> call(_i9.MoveTaskParams? params) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue: _i4.Future<_i5.Result<_i6.Task>>.value(
              _i8.dummyValue<_i5.Result<_i6.Task>>(
                this,
                Invocation.method(#call, [params]),
              ),
            ),
          )
          as _i4.Future<_i5.Result<_i6.Task>>);
}

/// A class which mocks [AddTaskUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockAddTaskUseCase extends _i1.Mock implements _i10.AddTaskUseCase {
  MockAddTaskUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.TasksRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeTasksRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.TasksRepository);

  @override
  _i4.Future<_i5.Result<_i6.Task>> call(_i10.AddTaskParams? params) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue: _i4.Future<_i5.Result<_i6.Task>>.value(
              _i8.dummyValue<_i5.Result<_i6.Task>>(
                this,
                Invocation.method(#call, [params]),
              ),
            ),
          )
          as _i4.Future<_i5.Result<_i6.Task>>);
}

/// A class which mocks [UpdateTaskUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockUpdateTaskUseCase extends _i1.Mock implements _i11.UpdateTaskUseCase {
  MockUpdateTaskUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.TasksRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeTasksRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.TasksRepository);

  @override
  _i4.Future<_i5.Result<_i6.Task>> call(_i11.UpdateTaskParams? params) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue: _i4.Future<_i5.Result<_i6.Task>>.value(
              _i8.dummyValue<_i5.Result<_i6.Task>>(
                this,
                Invocation.method(#call, [params]),
              ),
            ),
          )
          as _i4.Future<_i5.Result<_i6.Task>>);
}

/// A class which mocks [CloseTaskUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockCloseTaskUseCase extends _i1.Mock implements _i12.CloseTaskUseCase {
  MockCloseTaskUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.TasksRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeTasksRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.TasksRepository);

  @override
  _i4.Future<_i5.Result<_i6.Task>> call(_i12.CloseTaskParams? params) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue: _i4.Future<_i5.Result<_i6.Task>>.value(
              _i8.dummyValue<_i5.Result<_i6.Task>>(
                this,
                Invocation.method(#call, [params]),
              ),
            ),
          )
          as _i4.Future<_i5.Result<_i6.Task>>);
}

/// A class which mocks [DeleteTaskUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockDeleteTaskUseCase extends _i1.Mock implements _i13.DeleteTaskUseCase {
  MockDeleteTaskUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.TasksRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeTasksRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.TasksRepository);

  @override
  _i4.Future<_i5.Result<void>> call(_i13.DeleteTaskParams? params) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue: _i4.Future<_i5.Result<void>>.value(
              _i8.dummyValue<_i5.Result<void>>(
                this,
                Invocation.method(#call, [params]),
              ),
            ),
          )
          as _i4.Future<_i5.Result<void>>);
}

/// A class which mocks [GetSections].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetSections extends _i1.Mock implements _i14.GetSections {
  MockGetSections() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.TasksRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeTasksRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.TasksRepository);

  @override
  _i4.Future<_i5.Result<List<_i15.Section>>> call(_i7.NoParams? params) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue: _i4.Future<_i5.Result<List<_i15.Section>>>.value(
              _i8.dummyValue<_i5.Result<List<_i15.Section>>>(
                this,
                Invocation.method(#call, [params]),
              ),
            ),
          )
          as _i4.Future<_i5.Result<List<_i15.Section>>>);
}
