import 'package:dio/dio.dart';
import 'package:retrofit/retrofit.dart';

import '../../features/tasks/data/models/project_model.dart';
import '../../features/tasks/data/models/section_model.dart';
import '../../features/tasks/data/models/task_model.dart';
import '../../features/tasks/data/models/task_request_models.dart';

part 'todoist_api.g.dart';

/// Retrofit-generated API client for the Todoist REST API.
///
/// This abstract class defines all the endpoints available in the Todoist API.
/// The implementation is generated by the `retrofit_generator` package.
///
/// All methods return model classes that can be converted to domain entities
/// using their `toEntity()` methods.
@RestApi(baseUrl: 'https://api.todoist.com')
abstract class TodoistApi {
  /// Creates a [TodoistApi] instance.
  ///
  /// The [dio] parameter is the HTTP client to use for requests.
  /// Optionally, a custom [baseUrl] can be provided to override the default.
  factory TodoistApi(Dio dio, {String? baseUrl}) = _TodoistApi;

  // Projects

  /// Retrieves all projects from the Todoist API.
  ///
  /// Returns a list of [ProjectModel] instances representing all projects
  /// accessible to the authenticated user.
  @GET('/api/v1/projects')
  Future<List<ProjectModel>> getProjects();

  /// Retrieves a specific project by its [id].
  ///
  /// Returns a [ProjectModel] instance for the project with the given [id].
  @GET('/api/v1/projects/{id}')
  Future<ProjectModel> getProject(@Path('id') String id);

  // Sections

  /// Retrieves sections from the Todoist API.
  ///
  /// Optionally filters sections by [projectId] if provided.
  ///
  /// Returns a list of [SectionModel] instances.
  @GET('/api/v1/sections')
  Future<List<SectionModel>> getSections({
    @Query('project_id') String? projectId,
  });

  /// Retrieves a specific section by its [id].
  ///
  /// Returns a [SectionModel] instance for the section with the given [id].
  @GET('/api/v1/sections/{id}')
  Future<SectionModel> getSection(@Path('id') String id);

  // Tasks

  /// Retrieves tasks from the Todoist API.
  ///
  /// Optionally filters tasks by [projectId] and/or [sectionId] if provided.
  ///
  /// Returns a list of [TaskModel] instances.
  @GET('/api/v1/tasks')
  Future<List<TaskModel>> getTasks({
    @Query('project_id') String? projectId,
    @Query('section_id') String? sectionId,
  });

  /// Retrieves a specific task by its [id].
  ///
  /// Returns a [TaskModel] instance for the task with the given [id].
  @GET('/api/v1/tasks/{id}')
  Future<TaskModel> getTask(@Path('id') String id);

  /// Creates a new task in Todoist.
  ///
  /// The [body] contains the task details to create.
  ///
  /// Returns the created [TaskModel] instance.
  @POST('/api/v1/tasks')
  Future<TaskModel> addTask(@Body() AddTaskBody body);

  /// Moves a task to a different project and/or section.
  ///
  /// The [id] is the task ID to move.
  /// The [body] contains the target project and/or section IDs.
  ///
  /// Returns the updated [TaskModel] instance.
  @POST('/api/v1/tasks/{id}/move')
  Future<TaskModel> moveTask(@Path('id') String id, @Body() MoveTaskBody body);

  /// Updates an existing task.
  ///
  /// The [id] is the task ID to update.
  /// The [body] contains the fields to update.
  ///
  /// Returns the updated [TaskModel] instance.
  @POST('/api/v1/tasks/{id}')
  Future<TaskModel> updateTask(
    @Path('id') String id,
    @Body() UpdateTaskBody body,
  );

  /// Deletes a task by its [id].
  ///
  /// This operation is permanent and cannot be undone.
  @DELETE('/api/v1/tasks/{id}')
  Future<void> deleteTask(@Path('id') String id);

  /// Closes (completes) a task by its [id].
  ///
  /// This marks the task as completed in Todoist.
  @POST('/api/v1/tasks/{id}/close')
  Future<void> closeTask(@Path('id') String id);
}
