// Mocks generated by Mockito 5.4.6 from annotations
// in time_tracking_kanaban/test/features/tasks/presentation/cubit/comments_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;
import 'package:time_tracking_kanaban/core/utils/result.dart' as _i5;
import 'package:time_tracking_kanaban/features/tasks/domain/entities/comment.dart'
    as _i6;
import 'package:time_tracking_kanaban/features/tasks/domain/repository/comments_repository.dart'
    as _i2;
import 'package:time_tracking_kanaban/features/tasks/domain/usecases/add_comment_usecase.dart'
    as _i8;
import 'package:time_tracking_kanaban/features/tasks/domain/usecases/delete_comment_usecase.dart'
    as _i10;
import 'package:time_tracking_kanaban/features/tasks/domain/usecases/get_task_comments_usecase.dart'
    as _i3;
import 'package:time_tracking_kanaban/features/tasks/domain/usecases/update_comment_usecase.dart'
    as _i9;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeCommentsRepository_0 extends _i1.SmartFake
    implements _i2.CommentsRepository {
  _FakeCommentsRepository_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [GetTaskComments].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetTaskComments extends _i1.Mock implements _i3.GetTaskComments {
  MockGetTaskComments() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.CommentsRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeCommentsRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.CommentsRepository);

  @override
  _i4.Future<_i5.Result<List<_i6.Comment>>> call(
    _i3.GetTaskCommentsParams? params,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue: _i4.Future<_i5.Result<List<_i6.Comment>>>.value(
              _i7.dummyValue<_i5.Result<List<_i6.Comment>>>(
                this,
                Invocation.method(#call, [params]),
              ),
            ),
          )
          as _i4.Future<_i5.Result<List<_i6.Comment>>>);
}

/// A class which mocks [AddComment].
///
/// See the documentation for Mockito's code generation for more information.
class MockAddComment extends _i1.Mock implements _i8.AddComment {
  MockAddComment() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.CommentsRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeCommentsRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.CommentsRepository);

  @override
  _i4.Future<_i5.Result<_i6.Comment>> call(_i8.AddCommentParams? params) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue: _i4.Future<_i5.Result<_i6.Comment>>.value(
              _i7.dummyValue<_i5.Result<_i6.Comment>>(
                this,
                Invocation.method(#call, [params]),
              ),
            ),
          )
          as _i4.Future<_i5.Result<_i6.Comment>>);
}

/// A class which mocks [UpdateComment].
///
/// See the documentation for Mockito's code generation for more information.
class MockUpdateComment extends _i1.Mock implements _i9.UpdateComment {
  MockUpdateComment() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.CommentsRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeCommentsRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.CommentsRepository);

  @override
  _i4.Future<_i5.Result<_i6.Comment>> call(_i9.UpdateCommentParams? params) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue: _i4.Future<_i5.Result<_i6.Comment>>.value(
              _i7.dummyValue<_i5.Result<_i6.Comment>>(
                this,
                Invocation.method(#call, [params]),
              ),
            ),
          )
          as _i4.Future<_i5.Result<_i6.Comment>>);
}

/// A class which mocks [DeleteComment].
///
/// See the documentation for Mockito's code generation for more information.
class MockDeleteComment extends _i1.Mock implements _i10.DeleteComment {
  MockDeleteComment() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.CommentsRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeCommentsRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.CommentsRepository);

  @override
  _i4.Future<_i5.Result<void>> call(_i10.DeleteCommentParams? params) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue: _i4.Future<_i5.Result<void>>.value(
              _i7.dummyValue<_i5.Result<void>>(
                this,
                Invocation.method(#call, [params]),
              ),
            ),
          )
          as _i4.Future<_i5.Result<void>>);
}
