// Mocks generated by Mockito 5.4.6 from annotations
// in time_tracking_kanaban/test/features/tasks/data/repositories/tasks_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;

import 'package:connectivity_plus/connectivity_plus.dart' as _i16;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i12;
import 'package:time_tracking_kanaban/core/network/connectivity_service.dart'
    as _i15;
import 'package:time_tracking_kanaban/core/utils/result.dart' as _i10;
import 'package:time_tracking_kanaban/features/tasks/data/datasources/tasks_local_datasource.dart'
    as _i9;
import 'package:time_tracking_kanaban/features/tasks/data/datasources/todoist_api.dart'
    as _i6;
import 'package:time_tracking_kanaban/features/tasks/data/models/comment_model.dart'
    as _i5;
import 'package:time_tracking_kanaban/features/tasks/data/models/project_model.dart'
    as _i2;
import 'package:time_tracking_kanaban/features/tasks/data/models/section_model.dart'
    as _i3;
import 'package:time_tracking_kanaban/features/tasks/data/models/task_model.dart'
    as _i4;
import 'package:time_tracking_kanaban/features/tasks/data/models/task_request_models.dart'
    as _i8;
import 'package:time_tracking_kanaban/features/tasks/domain/entities/project.dart'
    as _i13;
import 'package:time_tracking_kanaban/features/tasks/domain/entities/section.dart'
    as _i14;
import 'package:time_tracking_kanaban/features/tasks/domain/entities/task.dart'
    as _i11;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeProjectModel_0 extends _i1.SmartFake implements _i2.ProjectModel {
  _FakeProjectModel_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSectionModel_1 extends _i1.SmartFake implements _i3.SectionModel {
  _FakeSectionModel_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeTaskModel_2 extends _i1.SmartFake implements _i4.TaskModel {
  _FakeTaskModel_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCommentsResponse_3 extends _i1.SmartFake
    implements _i5.CommentsResponse {
  _FakeCommentsResponse_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCommentModel_4 extends _i1.SmartFake implements _i5.CommentModel {
  _FakeCommentModel_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [TodoistApi].
///
/// See the documentation for Mockito's code generation for more information.
class MockTodoistApi extends _i1.Mock implements _i6.TodoistApi {
  MockTodoistApi() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<List<_i2.ProjectModel>> getProjects() =>
      (super.noSuchMethod(
            Invocation.method(#getProjects, []),
            returnValue: _i7.Future<List<_i2.ProjectModel>>.value(
              <_i2.ProjectModel>[],
            ),
          )
          as _i7.Future<List<_i2.ProjectModel>>);

  @override
  _i7.Future<_i2.ProjectModel> getProject(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getProject, [id]),
            returnValue: _i7.Future<_i2.ProjectModel>.value(
              _FakeProjectModel_0(this, Invocation.method(#getProject, [id])),
            ),
          )
          as _i7.Future<_i2.ProjectModel>);

  @override
  _i7.Future<List<_i3.SectionModel>> getSections({String? projectId}) =>
      (super.noSuchMethod(
            Invocation.method(#getSections, [], {#projectId: projectId}),
            returnValue: _i7.Future<List<_i3.SectionModel>>.value(
              <_i3.SectionModel>[],
            ),
          )
          as _i7.Future<List<_i3.SectionModel>>);

  @override
  _i7.Future<_i3.SectionModel> getSection(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getSection, [id]),
            returnValue: _i7.Future<_i3.SectionModel>.value(
              _FakeSectionModel_1(this, Invocation.method(#getSection, [id])),
            ),
          )
          as _i7.Future<_i3.SectionModel>);

  @override
  _i7.Future<List<_i4.TaskModel>> getTasks({
    String? projectId,
    String? sectionId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getTasks, [], {
              #projectId: projectId,
              #sectionId: sectionId,
            }),
            returnValue: _i7.Future<List<_i4.TaskModel>>.value(
              <_i4.TaskModel>[],
            ),
          )
          as _i7.Future<List<_i4.TaskModel>>);

  @override
  _i7.Future<_i4.TaskModel> getTask(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getTask, [id]),
            returnValue: _i7.Future<_i4.TaskModel>.value(
              _FakeTaskModel_2(this, Invocation.method(#getTask, [id])),
            ),
          )
          as _i7.Future<_i4.TaskModel>);

  @override
  _i7.Future<_i4.TaskModel> addTask(_i8.AddTaskBody? body) =>
      (super.noSuchMethod(
            Invocation.method(#addTask, [body]),
            returnValue: _i7.Future<_i4.TaskModel>.value(
              _FakeTaskModel_2(this, Invocation.method(#addTask, [body])),
            ),
          )
          as _i7.Future<_i4.TaskModel>);

  @override
  _i7.Future<_i4.TaskModel> moveTask(String? id, _i8.MoveTaskBody? body) =>
      (super.noSuchMethod(
            Invocation.method(#moveTask, [id, body]),
            returnValue: _i7.Future<_i4.TaskModel>.value(
              _FakeTaskModel_2(this, Invocation.method(#moveTask, [id, body])),
            ),
          )
          as _i7.Future<_i4.TaskModel>);

  @override
  _i7.Future<_i4.TaskModel> updateTask(String? id, _i8.UpdateTaskBody? body) =>
      (super.noSuchMethod(
            Invocation.method(#updateTask, [id, body]),
            returnValue: _i7.Future<_i4.TaskModel>.value(
              _FakeTaskModel_2(
                this,
                Invocation.method(#updateTask, [id, body]),
              ),
            ),
          )
          as _i7.Future<_i4.TaskModel>);

  @override
  _i7.Future<void> deleteTask(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteTask, [id]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> closeTask(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#closeTask, [id]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<_i5.CommentsResponse> getComments({required String? taskId}) =>
      (super.noSuchMethod(
            Invocation.method(#getComments, [], {#taskId: taskId}),
            returnValue: _i7.Future<_i5.CommentsResponse>.value(
              _FakeCommentsResponse_3(
                this,
                Invocation.method(#getComments, [], {#taskId: taskId}),
              ),
            ),
          )
          as _i7.Future<_i5.CommentsResponse>);

  @override
  _i7.Future<_i5.CommentModel> addComment(_i5.CreateCommentBody? body) =>
      (super.noSuchMethod(
            Invocation.method(#addComment, [body]),
            returnValue: _i7.Future<_i5.CommentModel>.value(
              _FakeCommentModel_4(this, Invocation.method(#addComment, [body])),
            ),
          )
          as _i7.Future<_i5.CommentModel>);

  @override
  _i7.Future<_i5.CommentModel> updateComment(
    String? id,
    _i5.UpdateCommentBody? body,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateComment, [id, body]),
            returnValue: _i7.Future<_i5.CommentModel>.value(
              _FakeCommentModel_4(
                this,
                Invocation.method(#updateComment, [id, body]),
              ),
            ),
          )
          as _i7.Future<_i5.CommentModel>);

  @override
  _i7.Future<void> deleteComment(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteComment, [id]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);
}

/// A class which mocks [TasksLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockTasksLocalDataSource extends _i1.Mock
    implements _i9.TasksLocalDataSource {
  MockTasksLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<_i10.Result<void>> storeTaskEntity(
    _i11.Task? task, {
    bool? isSynced = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#storeTaskEntity, [task], {#isSynced: isSynced}),
            returnValue: _i7.Future<_i10.Result<void>>.value(
              _i12.dummyValue<_i10.Result<void>>(
                this,
                Invocation.method(
                  #storeTaskEntity,
                  [task],
                  {#isSynced: isSynced},
                ),
              ),
            ),
          )
          as _i7.Future<_i10.Result<void>>);

  @override
  _i7.Future<_i10.Result<void>> storeTask(
    _i4.TaskModel? task, {
    bool? isSynced = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#storeTask, [task], {#isSynced: isSynced}),
            returnValue: _i7.Future<_i10.Result<void>>.value(
              _i12.dummyValue<_i10.Result<void>>(
                this,
                Invocation.method(#storeTask, [task], {#isSynced: isSynced}),
              ),
            ),
          )
          as _i7.Future<_i10.Result<void>>);

  @override
  _i7.Future<_i10.Result<void>> cacheTasks(
    List<_i4.TaskModel>? tasks, {
    bool? clearExisting = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #cacheTasks,
              [tasks],
              {#clearExisting: clearExisting},
            ),
            returnValue: _i7.Future<_i10.Result<void>>.value(
              _i12.dummyValue<_i10.Result<void>>(
                this,
                Invocation.method(
                  #cacheTasks,
                  [tasks],
                  {#clearExisting: clearExisting},
                ),
              ),
            ),
          )
          as _i7.Future<_i10.Result<void>>);

  @override
  _i7.Future<_i10.Result<List<_i11.Task>>> getCachedTasks({
    String? projectId,
    String? sectionId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getCachedTasks, [], {
              #projectId: projectId,
              #sectionId: sectionId,
            }),
            returnValue: _i7.Future<_i10.Result<List<_i11.Task>>>.value(
              _i12.dummyValue<_i10.Result<List<_i11.Task>>>(
                this,
                Invocation.method(#getCachedTasks, [], {
                  #projectId: projectId,
                  #sectionId: sectionId,
                }),
              ),
            ),
          )
          as _i7.Future<_i10.Result<List<_i11.Task>>>);

  @override
  _i7.Future<_i10.Result<_i11.Task>> getCachedTask(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getCachedTask, [id]),
            returnValue: _i7.Future<_i10.Result<_i11.Task>>.value(
              _i12.dummyValue<_i10.Result<_i11.Task>>(
                this,
                Invocation.method(#getCachedTask, [id]),
              ),
            ),
          )
          as _i7.Future<_i10.Result<_i11.Task>>);

  @override
  _i7.Future<_i10.Result<void>> cacheProjects(
    List<_i2.ProjectModel>? projects,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#cacheProjects, [projects]),
            returnValue: _i7.Future<_i10.Result<void>>.value(
              _i12.dummyValue<_i10.Result<void>>(
                this,
                Invocation.method(#cacheProjects, [projects]),
              ),
            ),
          )
          as _i7.Future<_i10.Result<void>>);

  @override
  _i7.Future<_i10.Result<List<_i13.Project>>> getCachedProjects() =>
      (super.noSuchMethod(
            Invocation.method(#getCachedProjects, []),
            returnValue: _i7.Future<_i10.Result<List<_i13.Project>>>.value(
              _i12.dummyValue<_i10.Result<List<_i13.Project>>>(
                this,
                Invocation.method(#getCachedProjects, []),
              ),
            ),
          )
          as _i7.Future<_i10.Result<List<_i13.Project>>>);

  @override
  _i7.Future<_i10.Result<_i13.Project>> getCachedProject(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getCachedProject, [id]),
            returnValue: _i7.Future<_i10.Result<_i13.Project>>.value(
              _i12.dummyValue<_i10.Result<_i13.Project>>(
                this,
                Invocation.method(#getCachedProject, [id]),
              ),
            ),
          )
          as _i7.Future<_i10.Result<_i13.Project>>);

  @override
  _i7.Future<_i10.Result<void>> cacheSections(
    List<_i3.SectionModel>? sections, {
    bool? clearExisting = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #cacheSections,
              [sections],
              {#clearExisting: clearExisting},
            ),
            returnValue: _i7.Future<_i10.Result<void>>.value(
              _i12.dummyValue<_i10.Result<void>>(
                this,
                Invocation.method(
                  #cacheSections,
                  [sections],
                  {#clearExisting: clearExisting},
                ),
              ),
            ),
          )
          as _i7.Future<_i10.Result<void>>);

  @override
  _i7.Future<_i10.Result<List<_i14.Section>>> getCachedSections({
    String? projectId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getCachedSections, [], {#projectId: projectId}),
            returnValue: _i7.Future<_i10.Result<List<_i14.Section>>>.value(
              _i12.dummyValue<_i10.Result<List<_i14.Section>>>(
                this,
                Invocation.method(#getCachedSections, [], {
                  #projectId: projectId,
                }),
              ),
            ),
          )
          as _i7.Future<_i10.Result<List<_i14.Section>>>);

  @override
  _i7.Future<_i10.Result<_i14.Section>> getCachedSection(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getCachedSection, [id]),
            returnValue: _i7.Future<_i10.Result<_i14.Section>>.value(
              _i12.dummyValue<_i10.Result<_i14.Section>>(
                this,
                Invocation.method(#getCachedSection, [id]),
              ),
            ),
          )
          as _i7.Future<_i10.Result<_i14.Section>>);

  @override
  _i7.Future<_i10.Result<List<_i11.Task>>> getUnsyncedTasks() =>
      (super.noSuchMethod(
            Invocation.method(#getUnsyncedTasks, []),
            returnValue: _i7.Future<_i10.Result<List<_i11.Task>>>.value(
              _i12.dummyValue<_i10.Result<List<_i11.Task>>>(
                this,
                Invocation.method(#getUnsyncedTasks, []),
              ),
            ),
          )
          as _i7.Future<_i10.Result<List<_i11.Task>>>);

  @override
  _i7.Future<_i10.Result<void>> markTaskAsSynced(String? taskId) =>
      (super.noSuchMethod(
            Invocation.method(#markTaskAsSynced, [taskId]),
            returnValue: _i7.Future<_i10.Result<void>>.value(
              _i12.dummyValue<_i10.Result<void>>(
                this,
                Invocation.method(#markTaskAsSynced, [taskId]),
              ),
            ),
          )
          as _i7.Future<_i10.Result<void>>);

  @override
  _i7.Future<_i10.Result<void>> clearCache() =>
      (super.noSuchMethod(
            Invocation.method(#clearCache, []),
            returnValue: _i7.Future<_i10.Result<void>>.value(
              _i12.dummyValue<_i10.Result<void>>(
                this,
                Invocation.method(#clearCache, []),
              ),
            ),
          )
          as _i7.Future<_i10.Result<void>>);
}

/// A class which mocks [ConnectivityService].
///
/// See the documentation for Mockito's code generation for more information.
class MockConnectivityService extends _i1.Mock
    implements _i15.ConnectivityService {
  MockConnectivityService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Stream<List<_i16.ConnectivityResult>> get onConnectivityChanged =>
      (super.noSuchMethod(
            Invocation.getter(#onConnectivityChanged),
            returnValue: _i7.Stream<List<_i16.ConnectivityResult>>.empty(),
          )
          as _i7.Stream<List<_i16.ConnectivityResult>>);

  @override
  _i7.Future<bool> isConnected() =>
      (super.noSuchMethod(
            Invocation.method(#isConnected, []),
            returnValue: _i7.Future<bool>.value(false),
          )
          as _i7.Future<bool>);
}
