import 'package:get_it/get_it.dart';
import 'package:injectable/injectable.dart';

import 'di.config.dart';

/// Global GetIt instance for dependency injection.
///
/// This instance is used throughout the application to access registered
/// dependencies. Dependencies are registered using the `@injectable` annotation
/// and initialized by calling [configureDependencies].
final getIt = GetIt.instance;

/// Configures and initializes all dependencies in the application.
///
/// This function should be called once at application startup, typically in
/// the [main] function before running the app. It registers all classes
/// annotated with `@injectable`, `@singleton`, `@lazySingleton`, etc.
///
/// The configuration is generated by the `injectable_generator` package
/// based on annotations in the codebase.
@InjectableInit(
  initializerName: 'init',
  preferRelativeImports: true,
  asExtension: true,
)
void configureDependencies() => getIt.init();
