// Mocks generated by Mockito 5.4.6 from annotations
// in time_tracking_kanaban/test/mocks/comments_repository_mock.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;
import 'package:time_tracking_kanaban/core/utils/result.dart' as _i4;
import 'package:time_tracking_kanaban/features/tasks/domain/entities/comment.dart'
    as _i5;
import 'package:time_tracking_kanaban/features/tasks/domain/repository/comments_repository.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [CommentsRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockCommentsRepository extends _i1.Mock
    implements _i2.CommentsRepository {
  MockCommentsRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Result<List<_i5.Comment>>> getCommentsForTask(
    String? taskId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getCommentsForTask, [taskId]),
            returnValue: _i3.Future<_i4.Result<List<_i5.Comment>>>.value(
              _i6.dummyValue<_i4.Result<List<_i5.Comment>>>(
                this,
                Invocation.method(#getCommentsForTask, [taskId]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<List<_i5.Comment>>>);

  @override
  _i3.Future<_i4.Result<_i5.Comment>> addComment(
    String? taskId,
    String? content,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#addComment, [taskId, content]),
            returnValue: _i3.Future<_i4.Result<_i5.Comment>>.value(
              _i6.dummyValue<_i4.Result<_i5.Comment>>(
                this,
                Invocation.method(#addComment, [taskId, content]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<_i5.Comment>>);

  @override
  _i3.Future<_i4.Result<void>> deleteComment(String? commentId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteComment, [commentId]),
            returnValue: _i3.Future<_i4.Result<void>>.value(
              _i6.dummyValue<_i4.Result<void>>(
                this,
                Invocation.method(#deleteComment, [commentId]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<void>>);

  @override
  _i3.Future<_i4.Result<_i5.Comment>> updateComment(
    String? commentId,
    String? content,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateComment, [commentId, content]),
            returnValue: _i3.Future<_i4.Result<_i5.Comment>>.value(
              _i6.dummyValue<_i4.Result<_i5.Comment>>(
                this,
                Invocation.method(#updateComment, [commentId, content]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<_i5.Comment>>);

  @override
  _i3.Future<_i4.Result<void>> syncPendingChanges() =>
      (super.noSuchMethod(
            Invocation.method(#syncPendingChanges, []),
            returnValue: _i3.Future<_i4.Result<void>>.value(
              _i6.dummyValue<_i4.Result<void>>(
                this,
                Invocation.method(#syncPendingChanges, []),
              ),
            ),
          )
          as _i3.Future<_i4.Result<void>>);
}
