// Mocks generated by Mockito 5.4.6 from annotations
// in time_tracking_kanaban/test/mocks/tasks_repository_mock.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;
import 'package:time_tracking_kanaban/core/utils/result.dart' as _i4;
import 'package:time_tracking_kanaban/features/tasks/domain/entities/project.dart'
    as _i7;
import 'package:time_tracking_kanaban/features/tasks/domain/entities/section.dart'
    as _i8;
import 'package:time_tracking_kanaban/features/tasks/domain/entities/task.dart'
    as _i5;
import 'package:time_tracking_kanaban/features/tasks/domain/repository/tasks_repository.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [TasksRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockTasksRepository extends _i1.Mock implements _i2.TasksRepository {
  MockTasksRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Result<List<_i5.Task>>> getTasks({
    String? projectId,
    String? sectionId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getTasks, [], {
              #projectId: projectId,
              #sectionId: sectionId,
            }),
            returnValue: _i3.Future<_i4.Result<List<_i5.Task>>>.value(
              _i6.dummyValue<_i4.Result<List<_i5.Task>>>(
                this,
                Invocation.method(#getTasks, [], {
                  #projectId: projectId,
                  #sectionId: sectionId,
                }),
              ),
            ),
          )
          as _i3.Future<_i4.Result<List<_i5.Task>>>);

  @override
  _i3.Future<_i4.Result<_i5.Task>> getTask(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getTask, [id]),
            returnValue: _i3.Future<_i4.Result<_i5.Task>>.value(
              _i6.dummyValue<_i4.Result<_i5.Task>>(
                this,
                Invocation.method(#getTask, [id]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<_i5.Task>>);

  @override
  _i3.Future<_i4.Result<_i5.Task>> createTask(_i5.Task? task) =>
      (super.noSuchMethod(
            Invocation.method(#createTask, [task]),
            returnValue: _i3.Future<_i4.Result<_i5.Task>>.value(
              _i6.dummyValue<_i4.Result<_i5.Task>>(
                this,
                Invocation.method(#createTask, [task]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<_i5.Task>>);

  @override
  _i3.Future<_i4.Result<_i5.Task>> updateTask(_i5.Task? task) =>
      (super.noSuchMethod(
            Invocation.method(#updateTask, [task]),
            returnValue: _i3.Future<_i4.Result<_i5.Task>>.value(
              _i6.dummyValue<_i4.Result<_i5.Task>>(
                this,
                Invocation.method(#updateTask, [task]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<_i5.Task>>);

  @override
  _i3.Future<_i4.Result<_i5.Task>> moveTask(
    _i5.Task? task,
    String? projectId,
    String? sectionId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#moveTask, [task, projectId, sectionId]),
            returnValue: _i3.Future<_i4.Result<_i5.Task>>.value(
              _i6.dummyValue<_i4.Result<_i5.Task>>(
                this,
                Invocation.method(#moveTask, [task, projectId, sectionId]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<_i5.Task>>);

  @override
  _i3.Future<_i4.Result<void>> deleteTask(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteTask, [id]),
            returnValue: _i3.Future<_i4.Result<void>>.value(
              _i6.dummyValue<_i4.Result<void>>(
                this,
                Invocation.method(#deleteTask, [id]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<void>>);

  @override
  _i3.Future<_i4.Result<void>> closeTask(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#closeTask, [id]),
            returnValue: _i3.Future<_i4.Result<void>>.value(
              _i6.dummyValue<_i4.Result<void>>(
                this,
                Invocation.method(#closeTask, [id]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<void>>);

  @override
  _i3.Future<_i4.Result<List<_i7.Project>>> getProjects() =>
      (super.noSuchMethod(
            Invocation.method(#getProjects, []),
            returnValue: _i3.Future<_i4.Result<List<_i7.Project>>>.value(
              _i6.dummyValue<_i4.Result<List<_i7.Project>>>(
                this,
                Invocation.method(#getProjects, []),
              ),
            ),
          )
          as _i3.Future<_i4.Result<List<_i7.Project>>>);

  @override
  _i3.Future<_i4.Result<_i7.Project>> getProject(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getProject, [id]),
            returnValue: _i3.Future<_i4.Result<_i7.Project>>.value(
              _i6.dummyValue<_i4.Result<_i7.Project>>(
                this,
                Invocation.method(#getProject, [id]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<_i7.Project>>);

  @override
  _i3.Future<_i4.Result<List<_i8.Section>>> getSections({String? projectId}) =>
      (super.noSuchMethod(
            Invocation.method(#getSections, [], {#projectId: projectId}),
            returnValue: _i3.Future<_i4.Result<List<_i8.Section>>>.value(
              _i6.dummyValue<_i4.Result<List<_i8.Section>>>(
                this,
                Invocation.method(#getSections, [], {#projectId: projectId}),
              ),
            ),
          )
          as _i3.Future<_i4.Result<List<_i8.Section>>>);

  @override
  _i3.Future<_i4.Result<_i8.Section>> getSection(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getSection, [id]),
            returnValue: _i3.Future<_i4.Result<_i8.Section>>.value(
              _i6.dummyValue<_i4.Result<_i8.Section>>(
                this,
                Invocation.method(#getSection, [id]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<_i8.Section>>);
}
