// Mocks generated by Mockito 5.4.6 from annotations
// in time_tracking_kanaban/test/mocks/timer_repository_mock.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;
import 'package:time_tracking_kanaban/core/utils/result.dart' as _i4;
import 'package:time_tracking_kanaban/features/timer/domain/entities/task_history_detail.dart'
    as _i8;
import 'package:time_tracking_kanaban/features/timer/domain/entities/task_timer_summary.dart'
    as _i7;
import 'package:time_tracking_kanaban/features/timer/domain/entities/time_log.dart'
    as _i5;
import 'package:time_tracking_kanaban/features/timer/domain/repository/timer_repository.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [TimerRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockTimerRepository extends _i1.Mock implements _i2.TimerRepository {
  MockTimerRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Result<_i5.TimeLog>> startTimer(String? taskId) =>
      (super.noSuchMethod(
            Invocation.method(#startTimer, [taskId]),
            returnValue: _i3.Future<_i4.Result<_i5.TimeLog>>.value(
              _i6.dummyValue<_i4.Result<_i5.TimeLog>>(
                this,
                Invocation.method(#startTimer, [taskId]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<_i5.TimeLog>>);

  @override
  _i3.Future<_i4.Result<_i5.TimeLog>> pauseTimer() =>
      (super.noSuchMethod(
            Invocation.method(#pauseTimer, []),
            returnValue: _i3.Future<_i4.Result<_i5.TimeLog>>.value(
              _i6.dummyValue<_i4.Result<_i5.TimeLog>>(
                this,
                Invocation.method(#pauseTimer, []),
              ),
            ),
          )
          as _i3.Future<_i4.Result<_i5.TimeLog>>);

  @override
  _i3.Future<_i4.Result<_i5.TimeLog>> resumeTimer(String? taskId) =>
      (super.noSuchMethod(
            Invocation.method(#resumeTimer, [taskId]),
            returnValue: _i3.Future<_i4.Result<_i5.TimeLog>>.value(
              _i6.dummyValue<_i4.Result<_i5.TimeLog>>(
                this,
                Invocation.method(#resumeTimer, [taskId]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<_i5.TimeLog>>);

  @override
  _i3.Future<_i4.Result<_i5.TimeLog>> stopTimer() =>
      (super.noSuchMethod(
            Invocation.method(#stopTimer, []),
            returnValue: _i3.Future<_i4.Result<_i5.TimeLog>>.value(
              _i6.dummyValue<_i4.Result<_i5.TimeLog>>(
                this,
                Invocation.method(#stopTimer, []),
              ),
            ),
          )
          as _i3.Future<_i4.Result<_i5.TimeLog>>);

  @override
  _i3.Future<_i4.Result<_i5.TimeLog?>> getActiveTimer() =>
      (super.noSuchMethod(
            Invocation.method(#getActiveTimer, []),
            returnValue: _i3.Future<_i4.Result<_i5.TimeLog?>>.value(
              _i6.dummyValue<_i4.Result<_i5.TimeLog?>>(
                this,
                Invocation.method(#getActiveTimer, []),
              ),
            ),
          )
          as _i3.Future<_i4.Result<_i5.TimeLog?>>);

  @override
  _i3.Future<_i4.Result<List<_i5.TimeLog>>> getTimeLogsForTask(
    String? taskId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getTimeLogsForTask, [taskId]),
            returnValue: _i3.Future<_i4.Result<List<_i5.TimeLog>>>.value(
              _i6.dummyValue<_i4.Result<List<_i5.TimeLog>>>(
                this,
                Invocation.method(#getTimeLogsForTask, [taskId]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<List<_i5.TimeLog>>>);

  @override
  _i3.Future<_i4.Result<_i7.TaskTimerSummary>> getTaskTimerSummary(
    String? taskId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getTaskTimerSummary, [taskId]),
            returnValue: _i3.Future<_i4.Result<_i7.TaskTimerSummary>>.value(
              _i6.dummyValue<_i4.Result<_i7.TaskTimerSummary>>(
                this,
                Invocation.method(#getTaskTimerSummary, [taskId]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<_i7.TaskTimerSummary>>);

  @override
  _i3.Future<_i4.Result<List<_i7.TaskTimerSummary>>>
  getCompletedTasksHistory() =>
      (super.noSuchMethod(
            Invocation.method(#getCompletedTasksHistory, []),
            returnValue:
                _i3.Future<_i4.Result<List<_i7.TaskTimerSummary>>>.value(
                  _i6.dummyValue<_i4.Result<List<_i7.TaskTimerSummary>>>(
                    this,
                    Invocation.method(#getCompletedTasksHistory, []),
                  ),
                ),
          )
          as _i3.Future<_i4.Result<List<_i7.TaskTimerSummary>>>);

  @override
  _i3.Future<_i4.Result<List<_i8.TaskHistoryDetail>>>
  getCompletedTasksHistoryDetailed() =>
      (super.noSuchMethod(
            Invocation.method(#getCompletedTasksHistoryDetailed, []),
            returnValue:
                _i3.Future<_i4.Result<List<_i8.TaskHistoryDetail>>>.value(
                  _i6.dummyValue<_i4.Result<List<_i8.TaskHistoryDetail>>>(
                    this,
                    Invocation.method(#getCompletedTasksHistoryDetailed, []),
                  ),
                ),
          )
          as _i3.Future<_i4.Result<List<_i8.TaskHistoryDetail>>>);
}
