import 'package:freezed_annotation/freezed_annotation.dart';

import '../../domain/entities/project.dart';

part 'project_model.freezed.dart';
part 'project_model.g.dart';

/// Data model representing a project from the Todoist API.
///
/// This model is used for JSON serialization/deserialization when communicating
/// with the Todoist API. It can be converted to a domain [Project] entity using
/// the [toEntity] method.
///
/// This class is generated by the `freezed` package and should not be
/// manually edited. Regenerate using `flutter pub run build_runner build`.
@freezed
abstract class ProjectModel with _$ProjectModel {
  const ProjectModel._();

  const factory ProjectModel({
    required String id,
    @JsonKey(name: 'can_assign_tasks') required bool canAssignTasks,
    @JsonKey(name: 'child_order') required int childOrder,
    required String color,
    @JsonKey(name: 'creator_uid') required String creatorUid,
    @JsonKey(name: 'created_at') required DateTime createdAt,
    @JsonKey(name: 'is_archived') required bool isArchived,
    @JsonKey(name: 'is_deleted') required bool isDeleted,
    @JsonKey(name: 'is_favorite') required bool isFavorite,
    @JsonKey(name: 'is_frozen') required bool isFrozen,
    required String name,
    @JsonKey(name: 'updated_at') required DateTime updatedAt,
    @JsonKey(name: 'view_style') required String viewStyle,
    @JsonKey(name: 'default_order') required int defaultOrder,
    required String description,
    @JsonKey(name: 'public_access') required bool publicAccess,
    @JsonKey(name: 'public_key') required String publicKey,
    required ProjectAccessModel access,
    required String role,
    @JsonKey(name: 'parent_id') String? parentId,
    @JsonKey(name: 'inbox_project') required bool inboxProject,
    @JsonKey(name: 'is_collapsed') required bool isCollapsed,
    @JsonKey(name: 'is_shared') required bool isShared,
  }) = _ProjectModel;

  /// Creates a [ProjectModel] from a JSON map.
  ///
  /// This method is generated by `json_serializable` and handles the conversion
  /// from the Todoist API JSON format to the model.
  factory ProjectModel.fromJson(Map<String, dynamic> json) =>
      _$ProjectModelFromJson(json);

  /// Converts this model to a domain [Project] entity.
  ///
  /// This method maps the data model fields to the domain entity, handling
  /// any necessary transformations.
  Project toEntity() => Project(
    id: id,
    canAssignTasks: canAssignTasks,
    childOrder: childOrder,
    color: color,
    creatorUid: creatorUid,
    createdAt: createdAt,
    isArchived: isArchived,
    isDeleted: isDeleted,
    isFavorite: isFavorite,
    isFrozen: isFrozen,
    name: name,
    updatedAt: updatedAt,
    viewStyle: viewStyle,
    defaultOrder: defaultOrder,
    description: description,
    publicAccess: publicAccess,
    publicKey: publicKey,
    access: access.toEntity(),
    role: role,
    parentId: parentId,
    inboxProject: inboxProject,
    isCollapsed: isCollapsed,
    isShared: isShared,
  );
}

/// Data model representing project access configuration from the Todoist API.
///
/// This model is used for JSON serialization/deserialization when communicating
/// with the Todoist API. It can be converted to a domain [ProjectAccess] entity
/// using the [toEntity] method.
///
/// This class is generated by the `freezed` package and should not be
/// manually edited. Regenerate using `flutter pub run build_runner build`.
@freezed
abstract class ProjectAccessModel with _$ProjectAccessModel {
  const ProjectAccessModel._();

  const factory ProjectAccessModel({
    required String visibility,
    required Map<String, dynamic> configuration,
  }) = _ProjectAccessModel;

  /// Creates a [ProjectAccessModel] from a JSON map.
  ///
  /// This method is generated by `json_serializable` and handles the conversion
  /// from the Todoist API JSON format to the model.
  factory ProjectAccessModel.fromJson(Map<String, dynamic> json) =>
      _$ProjectAccessModelFromJson(json);

  /// Converts this model to a domain [ProjectAccess] entity.
  ///
  /// This method maps the data model fields to the domain entity.
  ProjectAccess toEntity() =>
      ProjectAccess(visibility: visibility, configuration: configuration);
}
