import 'package:freezed_annotation/freezed_annotation.dart';

import '../../domain/entities/section.dart';

part 'section_model.freezed.dart';
part 'section_model.g.dart';

/// Data model representing a section from the Todoist API.
///
/// This model is used for JSON serialization/deserialization when communicating
/// with the Todoist API. It can be converted to a domain [Section] entity using
/// the [toEntity] method.
///
/// This class is generated by the `freezed` package and should not be
/// manually edited. Regenerate using `flutter pub run build_runner build`.
@freezed
abstract class SectionModel with _$SectionModel {
  const SectionModel._();

  const factory SectionModel({
    required String id,
    @JsonKey(name: 'user_id') required String userId,
    @JsonKey(name: 'project_id') required String projectId,
    @JsonKey(name: 'added_at') required DateTime addedAt,
    @JsonKey(name: 'updated_at') required DateTime updatedAt,
    @JsonKey(name: 'archived_at') DateTime? archivedAt,
    required String name,
    @JsonKey(name: 'section_order') required int sectionOrder,
    @JsonKey(name: 'is_archived') required bool isArchived,
    @JsonKey(name: 'is_deleted') required bool isDeleted,
    @JsonKey(name: 'is_collapsed') required bool isCollapsed,
  }) = _SectionModel;

  /// Creates a [SectionModel] from a JSON map.
  ///
  /// This method is generated by `json_serializable` and handles the conversion
  /// from the Todoist API JSON format to the model.
  factory SectionModel.fromJson(Map<String, dynamic> json) =>
      _$SectionModelFromJson(json);

  /// Converts this model to a domain [Section] entity.
  ///
  /// This method maps the data model fields to the domain entity, handling
  /// any necessary transformations.
  Section toEntity() => Section(
    id: id,
    userId: userId,
    projectId: projectId,
    addedAt: addedAt,
    updatedAt: updatedAt,
    archivedAt: archivedAt,
    name: name,
    sectionOrder: sectionOrder,
    isArchived: isArchived,
    isDeleted: isDeleted,
    isCollapsed: isCollapsed,
  );
}
