import 'package:freezed_annotation/freezed_annotation.dart';

import '../../domain/entities/task.dart';

part 'task_model.freezed.dart';
part 'task_model.g.dart';

/// Data model representing a task from the Todoist API.
///
/// This model is used for JSON serialization/deserialization when communicating
/// with the Todoist API. It can be converted to a domain [Task] entity using
/// the [toEntity] method.
///
/// This class is generated by the `freezed` package and should not be
/// manually edited. Regenerate using `flutter pub run build_runner build`.
@freezed
abstract class TaskModel with _$TaskModel {
  const TaskModel._();

  const factory TaskModel({
    @JsonKey(name: 'user_id') required String userId,
    required String id,
    @JsonKey(name: 'project_id') required String projectId,
    @JsonKey(name: 'section_id') String? sectionId,
    @JsonKey(name: 'parent_id') String? parentId,
    @JsonKey(name: 'added_by_uid') required String addedByUid,
    @JsonKey(name: 'assigned_by_uid') String? assignedByUid,
    @JsonKey(name: 'responsible_uid') String? responsibleUid,
    required List<String> labels,
    DateTime? deadline,
    int? duration,
    @JsonKey(name: 'checked') required bool checked,
    @JsonKey(name: 'is_deleted') required bool isDeleted,
    @JsonKey(name: 'added_at') required DateTime addedAt,
    @JsonKey(name: 'completed_at') DateTime? completedAt,
    @JsonKey(name: 'completed_by_uid') String? completedByUid,
    @JsonKey(name: 'updated_at') required DateTime updatedAt,
    @JsonKey(name: 'due_date') DateTime? due,
    required int priority,
    @JsonKey(name: 'child_order') required int childOrder,
    required String content,
    required String description,
    @JsonKey(name: 'note_count') required int noteCount,
    @JsonKey(name: 'day_order') required int dayOrder,
    @JsonKey(name: 'is_collapsed') required bool isCollapsed,
  }) = _TaskModel;

  /// Creates a [TaskModel] from a JSON map.
  ///
  /// This method is generated by `json_serializable` and handles the conversion
  /// from the Todoist API JSON format to the model.
  factory TaskModel.fromJson(Map<String, dynamic> json) =>
      _$TaskModelFromJson(json);

  /// Converts this model to a domain [Task] entity.
  ///
  /// This method maps the data model fields to the domain entity, handling
  /// any necessary transformations.
  Task toEntity() => Task(
    userId: userId,
    id: id,
    projectId: projectId,
    sectionId: sectionId ?? '',
    parentId: parentId,
    addedByUid: addedByUid,
    assignedByUid: assignedByUid,
    responsibleUid: responsibleUid,
    labels: labels,
    deadline: deadline,
    duration: duration,
    checked: this.checked,
    isDeleted: isDeleted,
    addedAt: addedAt,
    completedAt: completedAt,
    completedByUid: completedByUid,
    updatedAt: updatedAt,
    due: due,
    priority: priority,
    childOrder: childOrder,
    content: content,
    description: description,
    noteCount: noteCount,
    dayOrder: dayOrder,
    isCollapsed: isCollapsed,
  );
}
