import 'package:freezed_annotation/freezed_annotation.dart';

part 'task_request_models.freezed.dart';
part 'task_request_models.g.dart';

/// Request body model for creating a new task in the Todoist API.
///
/// This model is used when sending POST requests to create tasks.
/// It contains all the fields that can be set when creating a task.
///
/// This class is generated by the `freezed` package and should not be
/// manually edited. Regenerate using `flutter pub run build_runner build`.
@freezed
abstract class AddTaskBody with _$AddTaskBody {
  const factory AddTaskBody({
    /// Task content (title)
    required String content,

    /// Optional description
    String? description,

    /// Target project
    @JsonKey(name: 'project_id') String? projectId,

    /// Target section
    @JsonKey(name: 'section_id') String? sectionId,

    /// Labels attached to the task
    List<String>? labels,

    /// Priority 1-4
    int? priority,

    /// Due date string (e.g. "2025-12-02")
    @JsonKey(name: 'due_date') String? dueDate,

    /// Natural language due date language
    @JsonKey(name: 'due_lang') String? dueLang,
  }) = _AddTaskBody;

  /// Creates an [AddTaskBody] from a JSON map.
  ///
  /// This method is generated by `json_serializable`.
  factory AddTaskBody.fromJson(Map<String, dynamic> json) =>
      _$AddTaskBodyFromJson(json);
}

/// Request body model for moving a task in the Todoist API.
///
/// This model is used when sending POST requests to move tasks to different
/// projects or sections.
///
/// This class is generated by the `freezed` package and should not be
/// manually edited. Regenerate using `flutter pub run build_runner build`.
@freezed
abstract class MoveTaskBody with _$MoveTaskBody {
  const factory MoveTaskBody({
    /// The ID of the target project.
    @JsonKey(name: 'project_id') String? projectId,

    /// The ID of the target section.
    @JsonKey(name: 'section_id') String? sectionId,
  }) = _MoveTaskBody;

  /// Creates a [MoveTaskBody] from a JSON map.
  ///
  /// This method is generated by `json_serializable`.
  factory MoveTaskBody.fromJson(Map<String, dynamic> json) =>
      _$MoveTaskBodyFromJson(json);
}

/// Request body model for updating a task in the Todoist API.
///
/// This model is used when sending POST requests to update existing tasks.
/// Only the fields that need to be updated need to be provided.
///
/// This class is generated by the `freezed` package and should not be
/// manually edited. Regenerate using `flutter pub run build_runner build`.
@freezed
abstract class UpdateTaskBody with _$UpdateTaskBody {
  const factory UpdateTaskBody({
    /// The updated task content (title).
    String? content,

    /// The updated task description.
    String? description,

    /// The updated list of label IDs.
    List<String>? labels,

    /// The updated due date string (e.g., "2025-12-02").
    @JsonKey(name: 'due_date') String? dueDate,
  }) = _UpdateTaskBody;

  /// Creates an [UpdateTaskBody] from a JSON map.
  ///
  /// This method is generated by `json_serializable`.
  factory UpdateTaskBody.fromJson(Map<String, dynamic> json) =>
      _$UpdateTaskBodyFromJson(json);
}
